NUMPY Library

In [29]:
#module importing 
import numpy as np

In [30]:
#Using Array 
A=np.array(5)
A

array(5)

In [31]:
#Finding dimension of that Array
np.ndim(A)

0

In [32]:
#1D array
one=np.array([1,2,3,4,5])
one

array([1, 2, 3, 4, 5])

In [33]:
np.ndim(one)

1

In [34]:
# Dimensions in Arrays

#Create arrays of different dimentions.
#a=A numpy array with one single integer 10
#b=A numpy array passing a list having a list= [1,2,3]
#c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements
#d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements


#define a,b,c and d as instructed above

a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [35]:
#print dimentions of a,b, c and d
#np.ndim(a)
#np.ndim(b)
np.ndim(c)
#np.ndim(d)

2

Let's check its shape

In [36]:
# print shape of each a,b ,c and d
np.shape(a)
np.shape(b)
np.shape(c)
np.shape(d)

(2, 2, 3)

In [37]:
#Let's Check data type
print(type(c))
print(type(d))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [38]:
# Lets check length of array b, using len() function
# len(b)
a = np.array(10)
b = np.array([1,2,3])
print(a.size)   # 1
print(b.size)   # 3

1
3


In [39]:
#2D Array
two=np.array([[1,2,3],[2,4,3,]])
two

array([[1, 2, 3],
       [2, 4, 3]])

In [40]:
#3D Array
Three=np.array([[[1,2,3],[2,4,3,]],[[4,5,6,],[9,8,3]],[[0,3,1],[3,4,2]]])
Three

array([[[1, 2, 3],
        [2, 4, 3]],

       [[4, 5, 6],
        [9, 8, 3]],

       [[0, 3, 1],
        [3, 4, 2]]])

In [41]:
#np.ndim(one)
#np.ndim(two)
np.ndim(Three)

3

In [42]:
list=np.array([1,2,3,4])
array=np.array([1,2.3,'apple']) #Type conversion
array

array(['1', '2.3', 'apple'], dtype='<U32')

Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [43]:
# Define l1,l2,l3 and l4 as stated above.
l1 = np.array([1,2,3])
l2 = np.array([4,5,6])
l3 = np.array(l1)
l4 = np.array(l2)

In [44]:
#Create a numpy array using arange with 1 and 11 as parameter in it

import numpy as np

arr = np.arange(1, 11)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


In [45]:
# Create an array using arange passing 1,11 and 2 as parameter in iter

import numpy as np

arr = np.arange(1,11,2)
print(arr)

[1 3 5 7 9]


In [46]:
# create numpy array using eye function with 3 as passed parameter

arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
# Using arange() to generate numpy array x with numbers between 1 to 16
x=np.arange(1,17)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [48]:
# Reshape x with 2 rows and 8 columns
import numpy as np

# Example x with 16 elements
x = np.arange(1, 17)

# Reshape to 2 rows and 8 columns
x_reshaped = x.reshape(2, 8)
print(x_reshaped)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array

In [49]:
# reshaoe x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:
import numpy as np
x = np.arange(1, 17)
x_reshaped=x.reshape(2,4,2)
print(x_reshaped)


[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [50]:
# Use unknown dimention to reshape x into 2-D numpy array with shape 4*4
import numpy as np
x = np.arange(1, 17)
x_reshaped=x.reshape(4,4)
print(x_reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [51]:
# Create an array a with all even numbers between 1 to 17
import numpy as np
a = np.arange(2, 18, 2)
print(a)

[ 2  4  6  8 10 12 14 16]


In [52]:
#Print 3rd, 5th, and 7th element in array a
print(a[2])
print(a[4])
print(a[6])

6
10
14


In [53]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
# print the 3rd element from the 3rd row of a
print(a[2])

[7 8 9]


In [55]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
# b = 
b=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [56]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.

print(a[2])


[7 8 9]


In [57]:
# Create 1D array
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

In [58]:
# Slice elements from 1st to 5th element from the following array:
print(arr[:5])


[1 2 3 4 5]
